---
title: "plotly"
author: "MeOak Place"
date: "November 15, 2017"
output: html_document
---

```{r echo = FALSE, results = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidytext)
library(curl)
library(data.table)
library(dplyr)
library(DT)
library(forcats)
library(ggplot2)
library(ggridges)
library(ggthemes)
library(haven)
library(htmltools)
library(httr)
library(janitor)
library(jsonlite)
library(knitr)
library(magrittr)
library(plotly)
library(readr)
library(readxl)
library(reshape2)
library(rvest)
library(stringr)
library(tools)
library(viridisLite)
library(viridis)


devtools::install_github('hadley/ggplot2')


knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, message = FALSE, results = FALSE, warning = FALSE}
set.seed(1)

airbnb_data = read_csv("./data/nyc_airbnb.csv") %>%
  clean_names() %>%
  mutate(rating = review_scores_location / 2) %>%
  select(boro = neighbourhood_group, neighbourhood, rating, price, room_type,
         latitude, longitude) %>%
  filter(!is.na(rating), 
         boro == "Manhattan",
         room_type == "Entire home/apt",
         price %in% 100:500)  %>% 
  sample_n(5000)

#filtered to keep sample manageable for plotly
#can also code price > 100 & price < 400
```

Plotly Scatterplot
```{r echo = FALSE, message = FALSE, results = TRUE, warning = FALSE}
airbnb_data %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
```

Plotly Boxplot
```{r echo = FALSE, message = FALSE, results = TRUE, warning = FALSE}
common_neighborhoods =
  airbnb_data %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)
## Selecting by n

inner_join(airbnb_data, common_neighborhoods,
             by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% #orders according to highest median price
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

Plotly Barchart
```{r echo = FALSE, message = FALSE, results = TRUE, warning = FALSE}
airbnb_data %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar")
## Warning in RColorBrewer::brewer.pal(N, "Set2"): n too large, allowed maximum for palette Set2 is 8
## Returning the palette you asked for with that many colors
```

```{r echo = FALSE, message = FALSE, results = TRUE, warning = FALSE}
scatter_ggplot = airbnb_data %>%
  ggplot(aes(x = longitude, y = latitude, color = price)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() +
  theme_classic()

ggplotly(scatter_ggplot)
## Warning: We recommend that you use the dev version of ggplot2 with `ggplotly()`
## Install it with: `devtools::install_github('hadley/ggplot2')`
```


```{r echo = FALSE, message = FALSE, results = TRUE, warning = FALSE}
box_ggplot = 
  inner_join(airbnb_data, common_neighborhoods,
             by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot(aes(x = neighbourhood, y = price, fill = neighbourhood)) +
  geom_boxplot() +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplotly(box_ggplot)
```


flexdashboard
```{r}
library(flexdashboard)

```

